const jogos=[["MDM FC","2","1","Unidos"],["Ajax Cajobi","0","0","Resenha FC"]];
const tabela=[["MDM FC",10,4,3],["Ajax Cajobi",8,4,2],["Resenha FC",5,4,0],["Unidos",3,4,-2]];
export default function CampeonatoPublico(){return <main className="min-h-screen pb-28"><div className="mx-auto max-w-md">
  <section className="bg-gradient-to-b from-green-500/20 to-transparent px-5 pb-7 pt-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-green-400">COPEIRO · by MDM</p><div className="mt-6 flex items-center gap-4"><div className="grid h-20 w-20 place-items-center rounded-3xl bg-green-500 text-4xl">🏆</div><div><h1 className="text-3xl font-black">Copa Cajobi 2027</h1><p className="mt-1 text-sm text-zinc-400">Fut7 · Cajobi/SP</p></div></div></section>
  <div className="px-5"><div className="grid grid-cols-3 gap-2 rounded-2xl border border-white/10 bg-white/[.04] p-2 text-center text-sm font-bold"><span className="rounded-xl bg-green-500 px-2 py-3 text-black">Início</span><span className="px-2 py-3">Jogos</span><span className="px-2 py-3">Tabela</span></div>
  <h2 className="mb-3 mt-8 text-lg font-black">Últimos jogos</h2><div className="space-y-3">{jogos.map((j,i)=><div key={i} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-sm font-bold"><span>{j[0]}</span><strong className="rounded-lg bg-black/30 px-3 py-2 text-lg">{j[1]} × {j[2]}</strong><span className="text-right">{j[3]}</span></div></div>)}</div>
  <h2 className="mb-3 mt-8 text-lg font-black">Classificação</h2><div className="overflow-hidden rounded-2xl border border-white/10">{tabela.map((t,i)=><div key={String(t[0])} className="grid grid-cols-[28px_1fr_40px_40px] border-b border-white/10 bg-white/[.03] p-3 text-sm last:border-0"><b className="text-green-400">{i+1}</b><b>{t[0]}</b><span>{t[1]} pts</span><span>{t[2]}J</span></div>)}</div>
  </div></div>
  <nav className="fixed bottom-0 left-0 right-0 border-t border-white/10 bg-[#07110d]/95 px-3 py-3 backdrop-blur"><div className="mx-auto grid max-w-md grid-cols-5 text-center text-[11px] font-bold text-zinc-400"><span className="text-green-400">⌂<br/>Início</span><span>⚽<br/>Jogos</span><span>▤<br/>Classificação</span><span>◉<br/>Times</span><span>•••<br/>Mais</span></div></nav>
  </main>}